services:
  nginx-infotech:
    container_name: nginx-infotech
    image: nginx:1.24
    restart: "no"
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/
#      - ./.docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/config/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./.docker/config/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
    networks:
      - app-network-infotech

  php-infotech:
    build:
      context: ./.docker
    container_name: php-infotech
    restart: "no"
    working_dir: /var/www
    volumes:
      - .:/var/www/
    networks:
      - app-network-infotech

  mysql-infotech:
    container_name: mysql-infotech
    image: mysql:latest
    restart: "no"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-infotech:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network-infotech

networks:
  app-network-infotech:
    name: app-network-infotech
    driver: bridge

volumes:
  db-infotech:
    name: db-infotech